GET http://localhost:5001/task


###
POST http://localhost:5001/task
Content-Type: application/json


{
    "user":"Tom",
    "category":"Test",
    "taskText":"Testing creating and getting tasks :D"
}
