GET http://localhost:5001/task


###
POST http://localhost:5001/task
Content-Type: application/json


{
    "user":"Tom",
    "category":"Yeet",
    "taskText":"Test Deletin"
}

###
DELETE http://localhost:5001/task
Content-Type: application/json

{
    "_id":"69a655ccb2ced5d742152566"
}